baseUrl: $SERIOUS_SITE_URL_EN
enabled: true
handle: seriousWebsiteEn
hasUrls: true
language: en
name: serious-website-en
primary: false
siteGroup: 131ecefc-9bcc-432d-ae2a-17248a36ee73 # serious-website
sortOrder: 4
