baseUrl: 'http://serious.localhost:8080/de/'
enabled: true
handle: seriousWebsiteDe
hasUrls: true
language: de
name: serious-website-de
primary: false
siteGroup: 131ecefc-9bcc-432d-ae2a-17248a36ee73 # serious-website
sortOrder: 3
